config/routes.rb
DspaceRestRuby::Application.routes.draw do

  root to: "catalog#index"
  blacklight_for :catalog

  get "login/new"

  get '/communities', to: 'home#index'

  get '/about', to: 'home#about'

  get '/contact', to: 'home#contact'

  resources :community
  post :update, '/community/:id', to:'community#update'
  post :create, '/community' ,  to:'community#create'
  post :edit, '/community/:id/edit',  to:'community#edit'
  delete :destroy, '/community/:id', to:'community#destroy'
  post :update, '/community/:id', to:'community#update'

  resources :collection

  resources :item

  resources :login

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

      #caches_action :index, layout: true
      #caches_action :get_index_list, layout: false
      #caches_action :list_col, layout: false
     respond_to :json, :html

  # @return [@communities, @community_id, $base_rest_url, $endpoint, $json_node]
  def index

    @communities = Community.top
    @list = String.new
    get_index_list(@communities)


  end

  # Extremely slow... not sure if kb.osu.edu or code.
  def get_index_list(comlist)

    comlist.each do |com|

      @list += '<li class="tree">'
      @list += '<label for="'
      @list += com['name'][0,10] + '">'
      @list += self.class.helpers.link_to(com['name'], community_path(:id => com['id']))
      @list += '</label><input type="checkbox" id="' + com['name'][0,10] + '"/>'
    end
    @list += '</li>'
  end

  def list_col(collection_list)

    collection_list.each do |collection|
      @list += '<li class="file"><a href"'
      @list += self.class.helpers.link_to(collection['name'], collection_path(:id => collection['id']))
      @list += '</a></li>'

    end

  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/about.erb
<% $title = 'About' %>
<div class="page-header">
    <h2>DSpace Rails Project</h2>
</div>
<div class="container">
    <p>This project was developed to show the functionality of a Ruby on Rails application connected to DSpace Rest API.</p>
    <p>First developed by Mike Kalvas at Ohio State University.</p>
    <p>Updated/maintained by Peter Dietz (formerly of Ohio State University), and now at Longsight, to use DSpace 5 REST API.</p>
    <p>Tools used in creating this app:</p>
    <ul>
        <li><a href="http://www.ruby-lang.org/en/">Ruby Programming Language</a> </li>
        <li><a href="http://rubyonrails.org">Ruby on Rails</a></li>
        <li><a href="http://getbootstrap.com">Bootstrap</a></li>
        <li><a href="https://github.com/mkalvas/dspace-rest-rails">Github Repository Tracking</a></li>
        <li><a href="http://heroku.com">Heroku App Hosting</a></li>
    </ul>
    <button type="button" class="btn btn-default">
        <a href="https://github.com/mkalvas/dspace-rest-rails/commits/master">View Change Log</a>
    </button><br>
</div>

app/views/home/contact.erb
<% $title = 'Contact' %>
<div class="page-header">
    <h2>Contact Me</h2>
</div>
<div class="container">
<p>Feel free to contact me at any of the places below with anything regarding this application</p>
<ul>
    <li><a href="http://twitter.com/MikeKalvas">Twitter</a> </li>
    <li><a href="https://github.com/mkalvas">GitHub</a></li>
    <li><a href="mailto:mkalvas@gmail.com">Gmail</a></li>
    <li><a href="mailto:kalvas.2@osu.edu">OSU Email</a></li>
</ul>
</div>

app/views/home/index.html.erb
<% content_for :index do %>
    <% stylesheet_link_tag 'application' %>
<% end %>

<div class="jumbotron">
    <% $title = 'DSpace Communities' %>
    <h1><%= @communities.size %> Communities</h1>

    <ol class="tree">
        <%= @list.html_safe %>
    </ol>

    <%= render partial: 'shared/data_foot' %>

  <%= link_to 'New Community', new_community_path %>
</div>