config/routes.rb
DspaceRestRuby::Application.routes.draw do

  root to: "catalog#index"
  blacklight_for :catalog

  get "login/new"

  get '/communities', to: 'home#index'

  get '/about', to: 'home#about'

  get '/contact', to: 'home#contact'

  resources :community
  post :update, '/community/:id', to:'community#update'
  post :create, '/community' ,  to:'community#create'
  post :edit, '/community/:id/edit',  to:'community#edit'
  delete :destroy, '/community/:id', to:'community#destroy'
  post :update, '/community/:id', to:'community#update'

  resources :collection

  resources :item

  resources :login

end

app/models/community.rb
# app/models/person.rb
class Community <DspaceObject
  extend ActiveModel::Naming
  include ActiveModel::Conversion

  def persisted?
    false
  end

  attr_reader :community_name, :shortDescription

  def model_name
    @_model_name ="Community"
  end

  get :all, "/communities/"
  get :top, "/communities/top-communities"
  get :find, "/communities/:id"
  get :collections, "/communities/:id/collections"
  get :subcommunities, "/communities/:id/communities"
  put :save, "/communities/:id"
  delete :destroy, "/communities/:id"
  post :create, "/communities"
  post :logins , "/logins/",  plain: true

end

app/controllers/community_controller.rb
class CommunityController < HomeController


  def show
    @community = Community.find(params[:id])
    respond_with(@community)
  end

  def new
    @community = Community.new
    respond_with(@community)
  end

  def edit
    @community = Community.find(params[:id])
    respond_with(@community)
  end

  def create
    @community = Community.create(params[:community])
    flash[:notice] = 'community was successfully created.' unless @community.nil
     redirect_to communities_url, notice: 'community was successfully created.'
  end

  def update
    flash[:notice] = 'community was successfully updated.' if Community.save(params[:community])
    redirect_to communities_url
  end

  def destroy

    Community.destroy(params[:community])
      redirect_to communities_url, notice: 'community was successfully deleted.'
  end

end

app/helpers/community_helper.rb
module CommunityHelper
end

app/views/community/edit.erb
<h1>Edit Community</h1>

<%= simple_form_for @community, :url=>update_path do |f| %>
    <% value= @community.send("name") %>
    <%= f.input_field "name",  label: "Name",  input_html: {name: "community[name]", value: value, id: "community_name" } %>
    <%= f.hidden_field "id"  %>
    </br>
    <div class="class">
      <%= f.submit action_name="Edit Community" %>
    </div>
<% end %>

</br>
<%= link_to 'Show', @community %> |
<%= link_to 'Back', community_path %>

app/views/community/new.erb
<h1>Create Community</h1>

<%= simple_form_for @community, :url=>create_path do |f| %>
    <%= f.input_field "name"  %>
    <%= f.hidden_field "id"  %>
    <div class="class">
      <%= f.submit %>
    </div>
<% end %>

</br>
<%= link_to 'Show', @community %> |
<%= link_to 'Back', communities_url %>

app/views/community/show.erb
<div class="jumbotron">

    <div class="row">
        <div class="col-md-6">
            <% if !@community.parentCommunity.nil? %>
             <% #and @community.parentCommunity.size > 0 %>
                <p>Parent Communities</p>
                <li><%= link_to "#{@community.parentCommunity['name']}", community_path(:id => "#{@community.parentCommunity['id']}")%></li>
            <% end %>
        </div>
    </div>

    <% $title = 'Community' %>
    <h1><%= @community.name %></h1>

    <% unless @community.logo.nil? %>
        <img src=<%= $base_rest_url + @community.logo['retrieveLink'].to_s %>/>
    <% end %>

    <% unless @community.copyrightText.size < 1 %>
        <h2>Copyright Text</h2>
        <p><%= @community.copyrightText %></p>
    <% end %>

    <% unless @community.countItems.nil? %>
        <h2>Count Items: <%= @community.countItems %></h2>
    <% end %>

    <% unless @community.handle.nil? %>
        <p>Handle: <a href=<%= 'http://hdl.handle.net/' + @community.handle %>><%= 'http://hdl.handle.net/' + @community.handle %></a></p>
    <% end %>

    <% unless @community.introductoryText.size < 1 %>
        <h2>Introductory Text</h2>
        <p><%= strip_tags(@community.introductoryText) %></p>
    <% end %>

    <% unless @community.shortDescription.nil? %>
        <h2>Short Description</h2>
        <p><%= strip_tags(@community.shortDescription) %></p>
    <% end %>

    <% unless @community.sidebarText.size < 1 %>
        <h2>Sidebar Text</h2>
        <%= @community.sidebarText.html_safe %>
    <% end %>

  <% @subcommunities=Community.subcommunities(params[:id]) %>
    <% unless @subcommunities.empty? %>
        <h2>Communities within this Community</h2>
        <ul>
            <% @subcommunities.each do |subcommunity| %>
                <li>
                    <%= link_to "#{subcommunity['name']}", community_path(:id => "#{subcommunity['id']}") %>
                </li>
            <% end %>
        </ul>
    <% end %>

    <% @collections=Community.collections(params[:id]) %>
    <% unless @collections.empty? %>
        <h2>Collections within this Community</h2>
        <ul>
            <% @collections.each do |collection|%>
                <li>
                    <%= link_to "#{collection['name']}", collection_path(:id => "#{collection['id']}") %>
                </li>
            <% end %>
        </ul>
    <% end %>

    <%= render partial: 'shared/data_foot' %>
   <div>
  <%= simple_form_for @community, :url=>destroy_url, :method => "delete" do |f| %>
        <%= f.submit action_name="delete" %>
        <%= f.hidden_field "id" %>
  <% end %>
  <%= simple_form_for @community, :url=>edit_community_url, :method => "post" do |f| %>
  <%= f.submit action_name="edit" %>
  <%= f.hidden_field "id" %>
  <% end %>
     </div>
</div>