config/routes.rb
DspaceRestRuby::Application.routes.draw do

  root to: "catalog#index"
  blacklight_for :catalog

  get "login/new"

  get '/communities', to: 'home#index'

  get '/about', to: 'home#about'

  get '/contact', to: 'home#contact'

  resources :community
  post :update, '/community/:id', to:'community#update'
  post :create, '/community' ,  to:'community#create'
  post :edit, '/community/:id/edit',  to:'community#edit'
  delete :destroy, '/community/:id', to:'community#destroy'
  post :update, '/community/:id', to:'community#update'

  resources :collection

  resources :item

  resources :login

end

app/models/collection.rb
class Collection < DspaceObject

  get :all, "/collections/"
  get :find, "/collections/:id"
  get :items, "/collections/:id/items"
  post :logins , "/logins/",  plain: true
  put :save, "/collections/:id"
  post :create, "/collections"
end

app/controllers/collection_controller.rb
class CollectionController < CommunityController

  # @return [@collection, $base_rest_url, $endpoint, $json_node]
  def show

    @collection = Collection.find(params[:id])

    respond_with(@collection)

  end

end

app/helpers/collection_helper.rb
module CollectionHelper
end

app/views/collection/show.html.erb
<div class="jumbotron">

    <div class="row">
        <div class="col-md-6">
            <% if !@collection.parentCommunityList.nil? and @collection.parentCommunityList.size > 0 %>
                <% i = @collection.parentCommunityList.size %>
                <p>Parent Communities</p>
                <% while i > 0 %>
                    <li><%= link_to "#{@collection.parentCommunityList[i - 1]['name']}", community_path(:id => "#{@collection.parentCommunityList[i - 1]['id']}")%></li>
                    <% i -= 1 %>
                <% end %>
            <% end %>
        </div>
    </div>

    <% $title = 'Collection' %>
    <h1><%= @collection.name %></h1>

    <% unless @collection.logo.nil? %>
        <img src=<%= $base_rest_url + @collection.logo['retrieveLink'].to_s %>>
    <% end %>

    <% unless @collection.handle.nil? %>
        <p>Handle: <a href=<%= 'http://hdl.handle.net/' + @collection.handle %>><%= 'http://hdl.handle.net/' + @collection.handle %></a></p>
    <% end %>


    <% unless @collection.shortDescription.nil? %>
        <h2>Short Description</h2>
        <p><%= strip_tags(@collection.shortDescription) %></p>
    <% end %>

    <% unless @collection.numberItems.nil? %>
        <h2>This collection has <%= @collection.numberItems %> items</h2>
    <% end %>

  <% @items=Collection.items(params[:id]) %>
  <% unless @items.empty? %>
      <% @items.each do |item| %>
                <li>
                    <%= link_to "#{item['name']}", item_path(:id => "#{item['id']}") %>
                </li>
            <% end %>
        </ul>
    <% end %>

    <%= render partial: 'shared/data_foot' %>
</div>